#!/usr/bin/env bash
# Bash script to install nginx on your web-01 server

sudo apt update
sudo apt -y install nginx
sudo service nginx start
sudo chown -R $USER:$USER /var/www/html
echo "Holberton School" > /var/www/html/index.html
