#!/usr/bin/env bash
# Bash script to configure your Nginx server so that /redirect_me is redirecting to another page

sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
red="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "36i $red" /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload


