#!/usr/bin/env bash
# Configures a Nginx server to have a custom 404 page
sudo apt -y update
sudo apt -y install nginx
service nginx start
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html
red="\\\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}"
sudo sed -i "38i $red" /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload
