#!/usr/bin/env bash
#Script to configure a new server and add a custom NginX response header
sudo apt-get update
sudo apt-get upgrade
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo service nginx start
FILE="/etc/nginx/nginx.conf"
sudo sed -i "11i\\\tadd_header X-Served-By $HOSTNAME;" $FILE
sudo service nginx restart
sudo service nginx reload
