#!/usr/bin/env bash
# Script to configure HAproxy on your server load balancer
sudo apt update
sudo apt -y upgrade
sudo apt -y install haproxy=1.6.\*
FILE="/etc/haproxy/haproxy.cfg"
sudo echo "
frontend front
        bind *:80
        mode http
        default_backend backend-web

backend backend-web
        balance roundrobin
        server 2116-web-01 35.229.57.233:80 check
        server 2116-web-02 34.75.232.226:80 check" >> $FILE
sudo echo "ENABLED=1" >> /etc/default/haproxy
sudo service haproxy restart
