#!/usr/bin/env bash
# Script with the minimum number of commands to automate your fix
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
