#!/usr/bin/env bash
# This script displays the content of the file /etc/passwd
# The script only displays, username, user id and
# Home directory path for the user
while read -r line; do
    echo "$line" | cut -d':' -f 1,4,7
done < /etc/passwd
