#!/usr/bin/env bash
# Script that configures the container to fit the next requirements:
# nginx must be running as nginx user
# nginx must be listening on all active IPs on port 8080
# you cannot use apt-get remove

pkill apache2
chmod 644 /etc/nginx/nginx.conf
sed -i 's/80 default_/8080 default_/' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
