#!/usr/bin/env bash
# Script that does task #1

pkill apache2
chmod 644 /etc/nginx/nginx.conf
sed -i 's/80 default_/8080 default_/' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
